#!/usr/bin/env bash
# File transfers file given to server given as args
# Check if the number of arguments is less than 4

# Assign parameters to variables
file_path=$1
server_ip=$2
#username=$3
#ssh_key=$4

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$file_path" "ubuntu@$server_ip:~/"
